version: 2.0

default-docker-config: &default-docker-config
  docker:
    - image: circleci/ruby:2.5

jobs:
  build:
    # filters:
    #   branches:
    #     only:
    #       - staging
    <<: *default-docker-config

    steps:
      - checkout
      - run:
          name: Lint changed files
          command: ./ci-scripts/cf_login.sh
      - run:
          name: Rotate the credentials-rotator-user credentials
          command: ruby rotate_creds.rb credentials-rotator-user
      # - run:
      #     name: Rotate the federalist-deploy-user credentials
      #     command: ruby rotate_creds.rb federalist-deploy-user
      # - run:
      #     name: Rotate the ci-deploy-user credentials
      #     command: ruby rotate_creds.rb ci-deploy-user
      # - run:
      #     name: Delete stale federalist-deploy credentials
      #     command: ruby delete_service_keys.rb federalist-deploy-user
      # - run:
      #     name: Delete stale circleci credentials
      #     command: ruby delete_service_keys.rb ci-deploy-user

        
# workflows:
#   version: 2
#   nightly_staging:
#     jobs:
#       - build
#     triggers:
#       - schedule:
#         # every night at 6:11 AM UTC
#         cron: "11 06 * * *"
#         filters:
#           branches:
#             only:
#               - staging
