version: 2.0

default-docker-config: &default-docker-config
  docker:
    - image: circleci/ruby:2.5

jobs:
  rotate_credentials-rotator-user:
    <<: *default-docker-config

    steps:
      - checkout
      - run:
          name: login to cf
          command: bash ./ci-scripts/cf_login.sh
      - run:
          name: Rotate the credentials-rotator-user credentials
          command: ruby rotate_creds.rb credentials-rotator-user
      - run:
          name: Delete stale credentials-rotator-user credentials
          command: ruby delete_service_keys.rb credentials-rotator-user

  rotate_federalist-deploy-user:
    <<: *default-docker-config

    steps:
      - checkout
      - run:
          name: login to cf
          command: bash ./ci-scripts/cf_login.sh
      - run:
          name: Rotate the federalist-deploy-user credentials
          command: ruby rotate_creds.rb federalist-deploy-user
      - run:
          name: Delete stale federalist-deploy credentials
          command: ruby delete_service_keys.rb federalist-deploy-user

  rotate_ci-deploy-federalist-user:
    <<: *default-docker-config

    steps:
      - checkout
      - run:
          name: login to cf
          command: bash ./ci-scripts/cf_login.sh
      - run:
          name: Rotate the ci-deploy-federalist-user credentials
          command: ruby rotate_creds.rb ci-deploy-federalist-user
      - run:
          name: Delete stale ci-deploy-federalist-user credentials
          command: ruby delete_service_keys.rb ci-deploy-federalist-user
  
  rotate_ci-deploy-federalist-builder-user:
    <<: *default-docker-config

    steps:
      - checkout
      - run:
          name: login to cf
          command: bash ./ci-scripts/cf_login.sh
      - run:
          name: Rotate the ci-deploy-federalist-builder-user credentials
          command: ruby rotate_creds.rb ci-deploy-federalist-builder-user
      - run:
          name: Delete stale ci-deploy-federalist-builder-user credentials
          command: ruby delete_service_keys.rb ci-deploy-federalist-builder-user

        
workflows:
  version: 2