version: 2.0

default-docker-config: &default-docker-config
  docker:
    - image: circleci/ruby:2.5
      environment:
        # CF_ORGANIZATION: my_env
jobs:
  update_test_service:
    <<: *default-docker-config
    steps:
      - checkout
      - run:
          name: Activate venv and install requirements
          command: |
            curl -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            rm cf-cli_amd64.deb
            cf install-plugin autopilot -f -r CF-Community
            cf api $CF_API
            cf login -u $CF_USERNAME -p $CF_PASSWORD -o $CF_ORGANIZATION -s $CF_SPACE
      - run:
          name: Run tests against production instance
          command: ruby rotate_creds.rb test_service
        
workflows:
  version: 2
  login-and-rotate:
    jobs:
      - update_test_service
  # nightly:
  #   jobs:
  #     - prod-test
  #   triggers:
  #     - schedule:
  #         # every night at 2:11 AM UTC (10:11 PM ET)
  #         cron: "11 02 * * *"
  #         filters:
  #           branches:
  #             only:
  #               - master
