version: 2.0

default-docker-config: &default-docker-config
  docker:
    - image: circleci/ruby:2.5
      environment:
        # CF_ORGANIZATION: my_env
jobs:
  update_test_service:
    <<: *default-docker-config
    steps:
      - checkout
      - run:
          name: install CF CLI
          command: |
            curl -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            rm cf-cli_amd64.deb
            cf install-plugin autopilot -f -r CF-Community
            cf api $CF_API
            cf login -u $CF_TEST_USERNAME -p $CF_TEST_PASSWORD -o $CF_ORGANIZATION -s $CF_SPACE
      - run:
          name: Rotate the credentials
          command: ruby rotate_creds.rb test_service
      - run:
          name: Rotate the credentials
          command: ruby rotate_creds.rb test_circleci_service
      - run:
          name: Delete stale credentials
          command: ruby delete_service_keys.rb test_service 2
      - run:
          name: Delete stale circleci credentials
          command: ruby delete_service_keys.rb test_circleci_service 3
        
workflows:
  version: 2
  login-and-rotate:
    jobs:
      - update_test_service
  nightly:
    jobs:
      - update_test_service
    triggers:
      - schedule:
          # every night at 6:11 AM UTC
          cron: "11 06 * * *"
          filters:
            branches:
              only:
                - master
